#
# mozaik generic demo dashboard
#
# It's not required, but you should add this env var,
# without it, you'll probably reach the API rate limit.
#
# GITHUB_API_TOKEN=xxxxx
#
port: 5000

# define duraton between each dashboard rotation (ms)
rotationDuration: 10000

# This part of the config is neither watched nor
# transmitted to the UI as it might contain sensible info
apis:
  # define the global interval used by Mozaïk Bus to call registered APIs
  pollInterval: 100000

dashboards:
- columns: 4
  rows:    3
  title:   Mozaïk demo dashboard
  widgets:
  -
    extension:    github
    widget:       UserBadge
    user:         jadok
    columns:      1
    rows:         1
    x:            0
    y:            0

  -
    extension:    github
    widget:       RepoContributorsStats
    repository:   jadok/bet-extension
    columns:      1
    rows:         1
    x:            2
    y:            0
  -
    extension:    github
    widget:       RepoBadge
    repository:   jadok/bet-extension
    columns:      1
    rows:         1
    x:            3
    y:            0
  -
    extension:    mozaik
    widget:       Inspector
    columns:      1
    rows:         1
    x:            0
    y:            1
  -
    extension:    github
    widget:       Status
    columns:      1
    rows:         1
    x:            1
    y:            1
  -
    extension:    github
    widget:       Branches
    repository:   jadok/bet-extension
    columns:      1
    rows:         1
    x:            2
    y:            1
  -
    extension:    github
    widget:       PullRequests
    repository:   jadok/bet-extension
    columns:      1
    rows:         1
    x:            3
    y:            1

